require("dotenv").config();

const connectToMongo = require("./database/mongodb");
const mongoose = require("mongoose");
const express = require("express");
const cors = require("cors");
const req = require("express/lib/request");
const app = express();
const port = process.env.PORT || 443;

//for SSL/TLS
const fs = require('fs')
const https = require('https')

//use body-parser
const bodyParser = require("body-parser")
app.use(bodyParser.urlencoded({extended: true})) 
app.use(bodyParser.json()) 

// allow cross-origin requests
app.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );
  next();
});
app.use(express.json());
app.use(
  cors({
    origin: "*",
  })
);

//serve static file of SSL/TLS cert in hidden .well-known folder
app.use(express.static(__dirname + '/static', { dotfiles: 'allow' }))

//routes
const userRouter = require("./routers/userRoutes");
const articleRouter = require("./routers/articleRoutes");
const publishRouter = require("./routers/publishRoutes");

//Router
app.use("/api/v1/user", userRouter);
app.use("/api/v1/main", articleRouter);
app.use("/api/v1/articles", publishRouter);

//Server //pre SSL/TLS
// app.listen(port, async () => {
//   try {
//     await mongoose.connect(connectToMongo.uri, {
//       dbName: process.env.DB_NAME,
//       useNewUrlParser: true,
//       useUnifiedTopology: true,
//     });
//   } catch (err) {
//     console.log("Failed to connect to Mongo Atlas. Error is: ", err);
//     process.exit(1);
//   }

//   console.log(`Clog blogging system is listening on port ${port}`);
// });

//Server //with SSL/TLS
app.get('/', (req, res) => {
  res.send('HTTPS in use')
})


https
  .createServer(
    {
      //fill in the cert and key path generated by certbot 
      cert: fs.readFileSync('/etc/letsencrypt/.pem'),
      key: fs.readFileSync('/etc/letsencrypt/.pem'),
//      ca: fs.readFileSync('/etc/letsencrypt/.pem'),
    },
    app
  )

  .listen(port, async () => {
    try {
      await mongoose.connect(connectToMongo.uri, {
        dbName: process.env.DB_NAME,
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
    } catch (err) {
      console.log("Failed to connect to Mongo Atlas. Error is: ", err);
      process.exit(1);
    }

    console.log('Blog BE listening on ${port}')
  })

